language: php
php:
  - '7.1'

services:
  - mysql

before_install:
    - travis_retry composer self-update

install:
    - composer install
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
    - php bin/console doctrine:fixtures:load -n --env=test

script:
    - php src/CryptoConseils/BlogBundle/Resources/views/layout.html.twig

deploy:
    provider: heroku
    api_key: f40a8b67-f15f-4319-8ca6-4615cc221a77
    app: cryptoconseils

notifications:
    email: valentin.lenfant@hotmail.com

doctrine:
    dbal:
        url: "%env(DATABASE_URL)%"