cryptoconseils_users_index:
    path:    /users/
    defaults:
        _controller: CryptoConseilsUserBundle:User:index
        page: 1
    requirements:
        page: \d*


cryptoconseils_users_show:
    path:    /users/{username}
    defaults: { _controller: CryptoConseilsUserBundle:User:show }
    methods:    [GET]
    requirements:
        id: \d{1,} # Regular expression to find an id of integer type


cryptoconseils_users_edit:
    path:    /users/{username}
    defaults: { _controller: CryptoConseilsUserBundle:User:edit }
    methods:    [PUT]
    requirements:
        id: \d{1,}


cryptoconseils_users_delete:
    path:    /users/{username}
    defaults: { _controller: CryptoConseilsUserBundle:User:delete }
    methods:    [DELETE]
    requirements:
        id: \d{1,}


cryptoconseils_users_new:
    path:    /users/new/
    defaults: { _controller: CryptoConseilsUserBundle:User:new }
    methods:    [POST]

cryptoconseils_users_commentsByUsername:
    path:   /users/comments/username/{username}
    defaults: { _controller: CryptoConseilsUserBundle:User:showUserCommentsByUsername }
    methods:    [GET]

cryptoconseils_users_commentsById:
    path:   /users/comments/id/{id}
    defaults: { _controller: CryptoConseilsUserBundle:User:showUserCommentsById }
    methods:    [GET]

cryptoconseils_users_activateEmail:
    path:   /users/email/activate/
    defaults: { _controller: CryptoConseilsUserBundle:User:validateEmail }
    methods:    [POST]