######### Articles REST routes #########

cryptoconseils_blog_home:
    path:    /articles/
    defaults:
        _controller: CryptoConseilsBlogBundle:Article:index
        page: 1
    requirements:
        page: \d*

cryptoconseils_blog_show:
    path:    /articles/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Article:show }
    methods:    [GET]
    requirements:
        id: \d{1,} # Regular expression to find an id of integer type



cryptoconseils_blog_show_by_category:
    path:    /articles/category/{category}
    defaults: { _controller: CryptoConseilsBlogBundle:Article:show_by_category }
    methods:    [GET]


cryptoconseils_blog_show_by_newest:
    path:    /articles/newest/{number}
    defaults: { _controller: CryptoConseilsBlogBundle:Article:show_by_newest }
    methods:    [GET]



cryptoconseils_blog_edit:
    path:    /articles/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Article:edit }
    methods:    [PUT]
    requirements:
        id: \d{1,}


cryptoconseils_blog_delete:
    path:    /articles/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Article:delete }
    methods:    [DELETE]
    requirements:
        id: \d{1,}


cryptoconseils_blog_new:
    path:    /articles/new/
    defaults: { _controller: CryptoConseilsBlogBundle:Article:new }
    methods:    [POST]



######### Categories REST routes #########

cryptoconseils_blog_categories:
    path:    /categories/
    defaults: { _controller: CryptoConseilsBlogBundle:Category:index }
    methods:    [GET]


cryptoconseils_blog_category_show:
    path:    /categories/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Category:show }
    methods:    [GET]
    requirements:
        id: \d{1,} # Regular expression to find an id of integer type


cryptoconseils_blog_category_new:
    path:    /categories/new/
    defaults: { _controller: CryptoConseilsBlogBundle:Category:new }
    methods:    [POST]



cryptoconseils_blog_category_edit:
    path:    /categories/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Category:edit }
    methods:    [PUT]
    requirements:
        id: \d{1,}


cryptoconseils_blog_category_delete:
    path:    /categories/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Category:delete }
    methods:    [DELETE]
    requirements:
        id: \d{1,}



######### Comments REST routes #########

cryptoconseils_blog_comments:
    path:    /comments/
    defaults: { _controller: CryptoConseilsBlogBundle:Comment:index }
    methods:    [GET]


cryptoconseils_blog_comment_show:
    path:    /comments/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Comment:show }
    methods:    [GET]
    requirements:
        id: \d{1,} # Regular expression to find an id of integer type


cryptoconseils_blog_comment_new:
    path:    /comments/new/
    defaults: { _controller: CryptoConseilsBlogBundle:Comment:new }
    methods:    [POST]


cryptoconseils_blog_comment_edit:
    path:    /comments/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Comment:edit }
    methods:    [PUT]
    requirements:
        id: \d{1,}


cryptoconseils_blog_comment_delete:
    path:    /comments/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Comment:delete }
    methods:    [DELETE]
    requirements:
        id: \d{1,}


######### Images REST routes #########

cryptoconseils_blog_images:
    path:    /images/
    defaults: { _controller: CryptoConseilsBlogBundle:Image:index }
    methods:    [GET]


cryptoconseils_blog_image_show:
    path:    /images/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Image:show }
    methods:    [GET]
    requirements:
        id: \d{1,} # Regular expression to find an id of integer type


cryptoconseils_blog_image_new:
    path:    /images/new/
    defaults: { _controller: CryptoConseilsBlogBundle:Image:new }
    methods:    [POST]


cryptoconseils_blog_image_edit:
    path:    /images/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Image:edit }
    methods:    [PUT]
    requirements:
        id: \d{1,}

cryptoconseils_blog_image_delete:
    path:    /images/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Image:delete }
    methods:    [DELETE]
    requirements:
        id: \d{1,}

cryptoconseils_blog_orders_new:
    path:   /orders/new/{amount}
    defaults: { _controller: CryptoConseilsBlogBundle:Orders:new }

cryptoconseils_blog_orders_show:
    path:   /orders/show/{order}
    defaults: { _controller: CryptoConseilsBlogBundle:Orders:show }

cryptoconseils_blog_orders_paymentcreate:
    path:   /orders/payment/create/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Orders:paymentCreate }

cryptoconseils_blog_orders_paymentcomplete:
    path:   /orders/payment/complete/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Orders:paymentComplete }

cryptoconseils_blog_orders_paymentcancel:
    path:   /orders/payment/cancel/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Orders:paymentCancel }

cryptoconseils_blog_call_new:
    path:   /call/new/
    defaults: { _controller: CryptoConseilsBlogBundle:Calls:new }
    methods:    [POST]

cryptoconseils_blog_call_all:
    path:   /call/all/
    defaults: { _controller: CryptoConseilsBlogBundle:Calls:allCalls }
    methods:    [GET]

cryptoconseils_blog_call:
    path:   /call/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Calls:call }
    methods:    [GET]

cryptoconseils_blog_delete_call:
    path:   call/delete/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Calls:delete }
    methods:    [DELETE]

cryptoconseils_blog_new_contact:
    path:   contact/new
    defaults:   { _controller: CryptoConseilsBlogBundle:Contact:new }
    methods:    [POST]