cryptoconseils_blog_home:
    path:    /blog
    defaults: { _controller: CryptoConseilsBlogBundle:Article:index }

cryptoconseils_blog_view:
    path:    /blog/articles/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Article:view }
    requirements:
        id: \d{1,} # Regular expression to find an id of integer type

cryptoconseils_blog_add:
    path:    /blog/articles/add
    defaults: { _controller: CryptoConseilsBlogBundle:Article:add }

cryptoconseils_blog_edit:
    path:    /blog/articles/edit/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Article:edit }
    requirements:
        id: \d{1,}

cryptoconseils_blog_delete:
    path:    /blog/articles/delete/{id}
    defaults: { _controller: CryptoConseilsBlogBundle:Article:delete }
    requirements:
        id: \d{1,}